services:
  wg-quic-differentiator:
    profiles:
      - diff
    build:
      context: ./wg-quic-differentiator
      dockerfile: Dockerfile
    container_name: wg-quic-differentiator
    ports:
      - "8080:8080/udp"
    environment:
      - RUST_LOG=debug
    restart: unless-stopped
    depends_on:
      - wireguard
      - http3-server

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVER_PRIVATE_KEY=${SERVER_PRIVATE_KEY}
      - CLIENT_PUBLIC_KEY=${CLIENT_PUBLIC_KEY}
    env_file:
      - .env
    ports:
      - "51820:51820/udp"
    volumes:
      - ./wireguard/entrypoint.sh:/entrypoint.sh:ro
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    entrypoint: ["/bin/bash", "/entrypoint.sh"]

  http3-server:
    profiles:
      - basic-server
    build:
      context: ./http3-server
      dockerfile: Dockerfile
    container_name: http3-server
    ports:
      - "8443:8443/udp"
    restart: unless-stopped

  nginx-server:
    profiles:
      - nginx-server
    image: macbre/nginx-http3:latest
    container_name: nginx-server
    ports:
      - "8443:443/tcp"
      - "8443:443/udp"
    restart: unless-stopped
    volumes:
      - ./nginx-server/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx-server/ssl:/etc/nginx/ssl:ro
    command: sh -c "dd if=/dev/urandom of=/tmp/100mb.bin bs=1M count=10000 && nginx -g 'daemon off;'"

